from django.conf.urls import patterns, url

urlpatterns = patterns('ModelApp.views',
	url(r'^ServicesFundingModel/home/', 'home'),
	url(r'^ServicesFundingModel/about/$', 'about'),
	url(r'^ServicesFundingModel/setup/$', 'setup'),
	url(r'^ServicesFundingModel/setup/(GDRAT)/$', 'docUpload', name='GDRAT'),
	url(r'^ServicesFundingModel/setup/(Function)/$', 'docUpload', name='Function'),
	url(r'^ServicesFundingModel/setup/(HeadcountBIS)/$', 'docUpload', name='HeadcountBIS'),
	url(r'^ServicesFundingModel/setup/(HeadcountADJ)/$', 'docUpload', name='HeadcountADJ'),
	url(r'^ServicesFundingModel/setup/(Product)/$', 'docUpload', name='Product'),
	url(r'^ServicesFundingModel/setup/(ServicesMRR)/$', 'docUpload', name='ServicesMRR'),
	url(r'^ServicesFundingModel/setup/(ServicesNRR)/$', 'docUpload', name='ServicesNRR'),
	url(r'^ServicesFundingModel/setup/(MRRContract)/$', 'docUpload', name='MRRContract'),
	url(r'^ServicesFundingModel/setup/(PlatformProductFrcst)/$', 'docUpload', name='PlatformProductFrcst'),
	url(r'^ServicesFundingModel/setup/(GSSMRRFrcst)/$', 'docUpload', name='GSSMRRFrcst'),
	url(r'^ServicesFundingModel/setup/(GSSNRRFrcst)/$', 'docUpload', name='GSSNRRFrcst'),
	url(r'^ServicesFundingModel/setup/(\w+)/template/$', 'templateDownload'),
	url(r'^ServicesFundingModel/setup/(\w+)/instructions/$', 'instructions'),
	url(r'^ServicesFundingModel/view/$', 'view'),
	url(r'^ServicesFundingModel/view/function/(.+)/', 'viewFunction'),
	url(r'^ServicesFundingModel/view/headcount/(.+)/', 'viewHeadcount'),
	url(r'^ServicesFundingModel/view/product/(.+)/', 'viewProduct', name='product'),
	url(r'^ServicesFundingModel/view/workingValue/(.+)/', 'viewWorkingValue', name='workingValue'),
	url(r'^ServicesFundingModel/view/frcst/(.+)/(.+)/', 'viewForecast', name='forecast'),
	url(r'^ServicesFundingModel/exportDetailsForecast/(.+)/(.+)/$', 'exportDetailsForecast'),	
	url(r'^ServicesFundingModel/(run)/([\w\s]+)/', 'run'),
	url(r'^ServicesFundingModel/(runGap)/([\w\s]+)/', 'runReqs'),		
	url(r'^ServicesFundingModel/(runReqs)/([\w\s]+)/', 'runReqs'),		
	url(r'^ServicesFundingModel/exportDetailsRun/(\w+)/([\w\s]+)/$', 'exportDetailsRun'),
	url(r'^ServicesFundingModel/sandbox/$', 'sandbox'),	
	url(r'^ServicesFundingModel/contact/$', 'contact'),
	url(r'^ServicesFundingModel/setup/\w+/documents/$', 'documents'),
)